version: '3.9'
services:
  db:
    # amdかarmを選択する
    # image: postgres:15.1-alpine
    image: arm64v8/postgres:15.1-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./data:/db/conf/
    env_file:
      - .env
  go_api:
    build: .
    tty: true
    volumes:
      - .:/go/src
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c '
        air -c .air.toml
      '
volumes:
  dbdata: null
